imports:
    - { resource: tables.yml }

services:
    evilsystem.amxxmonitoring.controller.main:
        class: evilsystem\amxxmonitoring\controller\main_controller
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'
            - '@request'
            - '@dbal.conn'
            - '@user'
            - '%evilsystem.amxxmonitoring.tables.evilsystem_amxxmonitoring_mods%'
            - '%evilsystem.amxxmonitoring.tables.evilsystem_amxxmonitoring_table%'

    evilsystem.amxxmonitoring.controller.acp:
        class: evilsystem\amxxmonitoring\controller\acp_controller
        arguments:
            - '@config'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '%evilsystem.amxxmonitoring.tables.evilsystem_amxxmonitoring_mods%'
            - '%evilsystem.amxxmonitoring.tables.evilsystem_amxxmonitoring_table%'

    evilsystem.amxxmonitoring.controller.ucp:
        class: evilsystem\amxxmonitoring\controller\ucp_controller
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '%evilsystem.amxxmonitoring.tables.evilsystem_amxxmonitoring_mods%'
            - '%evilsystem.amxxmonitoring.tables.evilsystem_amxxmonitoring_table%'

    evilsystem.amxxmonitoring.listener:
        class: evilsystem\amxxmonitoring\event\main_listener
        arguments:
            - '@language'
            - '@controller.helper'
            - '@template'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
    evilsystem.amxxmonitoring.cron.task.servers:
        class: evilsystem\amxxmonitoring\cron\task\servers
        arguments:
            - '@config'
            - '%evilsystem.amxxmonitoring.tables.evilsystem_amxxmonitoring_table%'
        calls:
            - [set_name, [evilsystem.amxxmonitoring.cron.task.servers]]
        tags:
            - { name: cron.task }